version: "2.2"
services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        DOMAIN: 'cellphoneX.biz'
    container_name: cellphoneX_framework
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links: 
      - mysql
      - phpmyadmin

  mysql:
    image: mariadb:10
    container_name: cellphoneX_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cellphoneX_phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M